#!/usr/bin/env python3
import sys
import os.path
import yaml
import argparse
import fileinput
from urllib.parse import urljoin
import requests

APP_NAME = 'gotify-cli-app'
CONFIG_NAME = 'gotify'

config = None

def main():
    # Parde and declare arguments
    args = parseArgs()

    # Check if url argument supplied (if so, don't load config)
    url = parseURLAndConfig(args)
    # Load app token (either from map, from argument, or default from config)
    token = parseToken(args)
    # Load title (either from argument, or default from config)
    title = parseTitle(args)
    # Load message (either from argument, from stdin, or default from config)
    message = parseMessage(args)
    # Load priority (either from argument, or default from config)
    priority = parsePriority(args)

    # Perform request
    resp = doRequest(url, token, title, message, priority)

    # Print request result only if it fails
    if resp.status_code is not requests.codes.ok:
        sys.exit(bytes.decode(resp.content))

def parseArgs():
    # Argument parser declaration
    parser = argparse.ArgumentParser(description='Gotify cli')
    groupUrlOrConfig = parser.add_mutually_exclusive_group()
    groupUrlOrConfig.add_argument('-u', '--url', help='url of Gotify server (overrides config)')
    groupUrlOrConfig.add_argument('-c', '--config', help='file path of a yaml config file')
    groupTokenOrKey = parser.add_mutually_exclusive_group()
    groupTokenOrKey.add_argument('-a', '--app-token', help='gotify app token to which to send the notification')
    groupTokenOrKey.add_argument('-k', '--key', help='lookup token from key in the config file')
    parser.add_argument('-t', '--title', help='the title of the notification')
    parser.add_argument('-m', '--message', help='the message of the notification (\'-\' to read from stdin)')
    parser.add_argument('-p', '--priority', type=int, help='the priority of the notification')
    return parser.parse_args()

def parseURLAndConfig(args):
    # Declare variable config as reference to global config variable in this function
    global config
    if args.url:
        # This check is necessary since at this point in time argparse does not
        # yet support "necessarily inclusive" groups
        # (https://bugs.python.org/issue11588)
        if not (args.app_token and args.title and args.message) or args.key:
            sys.exit('The following arguments are required when using url argument:\n-a/--app-token -t/--title -m/--message -p/--priority\nAlso -k/--key argument may not be used with url argument')
        # Load url from argument
        return args.url
    else:
        # Load config
        if args.config:
            # Load config from path provided as argument
            config = loadConfig(args.config)
        else:
            # Load config file from predefined locations
            config = loadDefaultConfig()
        # Load url from config
        return config['url']

def parseToken(args):
    if args.key:
        return loadTokenFromKey(config, args.key)
    else:
        if args.app_token:
            return args.app_token
        else:
            return config['default']['token']

def parseTitle(args):
    if args.title:
        return args.title
    else:
        return config['default']['title']

def parseMessage(args):
    if args.message:
        return args.message
        if message is '-':
            return sys.stdin.buffer.read()
    else:
        return config['default']['message']

def parsePriority(args):
    if args.priority:
        return args.priority
    else:
        return config['default']['priority']

def loadConfig(configFile):
    if os.path.isfile(configFile):
        file = open(configFile, 'r')
        yamlString = file.read()
        file.close()
    else:
        sys.exit('Could not load config: ' + path)
    return yaml.load(yamlString)

def loadDefaultConfig():
    HOME = os.path.expanduser('~')
    configFileLocations = [
            '/etc/' + APP_NAME + '/' + CONFIG_NAME + '.yml',
            '/etc/' + APP_NAME + '/' + CONFIG_NAME + '.yaml',
            HOME + '/.' + APP_NAME + '/' + CONFIG_NAME + '.yml',
            HOME + '/.' + APP_NAME + '/' + CONFIG_NAME + '.yaml',
            HOME + '/.config/' + APP_NAME + '/' + CONFIG_NAME + '.yml',
            HOME + '/.config/' + APP_NAME + '/' + CONFIG_NAME + '.yaml',
            HOME + '.' + CONFIG_NAME + '.yml',
            HOME + '.' + CONFIG_NAME + '.yaml',
            './' + CONFIG_NAME + '.yml',
            './' + CONFIG_NAME + '.yaml'
    ]

    configLoaded = False

    # Load config files in array order (multiple configs will override each other)
    for configFile in configFileLocations:
        if os.path.isfile(configFile):
            file = open(configFile, 'r')
            yamlString = file.read()
            file.close()
            configLoaded = True

    # Exit with error if no config was loaded
    if not configLoaded:
        sys.exit('No config file found!')

    return yaml.load(yamlString)

def loadTokenFromKey(config, key):
    # Lookup if key exists in token Map
    if config['tokenMap'] is not None and key in config['tokenMap']:
        return config['tokenMap'][key]
    else:
        sys.exit('No such key found in config: ' + key)

def doRequest(url, token, title, message, priority):
    requestURL = urljoin(url, '/message?token=' + token)
    resp = requests.post(requestURL, json={
        'title': title,
        'message': message,
        'priority': priority
    })
    return resp

if __name__ == "__main__":
    main()
